Repository Sajiyah-Salat/BlogWeb, pull requests merged in 2022-10, with the labels that each got.

#20 added more detailed guidelines
  README.md
Labels: Hacktoberfest

#16 Added favicon to the website
  index.html
  src/img/favicon.png
Labels: Hacktoberfest

#17 I created a contribution guideline
  CONTRIBUTING.md
Labels: good first issue, Hacktoberfest

#14 Issue #4 Added Dark mode button to all pages
  blogspot.html
  blogspot2.html
  index.html
Labels: enhancement, Hacktoberfest

#28 Dev/design
  css/style.css
  css/util.css
  index.html
Labels: Hacktoberfest

#36 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, Hacktoberfest

#41 Changed design completely for home page
  images/about-us.jpg
  images/blogger.ico
  index.html
  index.js
  style.css
Labels: help wanted, Hacktoberfest
